# Generated by Django 3.1.3 on 2020-11-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='alamat',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pdf',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
