# Generated by Django 3.1.3 on 2020-11-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201126_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDiri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('foto', models.FileField(upload_to='penerima/foto/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
