# Generated by Django 3.1.3 on 2020-11-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201126_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadiri',
            name='foto',
            field=models.ImageField(upload_to='foto/'),
        ),
    ]
